#!/bin/bash

generate_go_const() {
  local varname=$1
  local htmlname=$2
  cat << EOS
const $varname = \`
EOS
  cat ./assets/$htmlname
  cat << EOS
\`
EOS
}

generate() {
  cat << EOS
package main

// generated by 'script/gen_html.sh'

EOS
  generate_go_const taishokuNegaiHTMLTemplate taishoku-negai.html.template
  generate_go_const taishokuTodokeHTMLTemplate taishoku-todoke.html.template
}

generate > template.go

